### ISSUE TITLE
ModuleNotFoundError: No module named 'type_func'

### ISSUE THREAD

**Issue by mk123qwe** [eric-moreno/IN#3]
ModuleNotFoundError: No module named 'type_func'
is there any package except install.sh?

**Comment by jmduarte** [comment]
Opened PR #4 to fix this @eric-moreno

**Comment by mk123qwe** [comment]
I have solved the problem with your suggestion and finished training.

**Comment by eric-moreno** [comment]
Also verified that these suggestions work with training, evaluation, and plotting.
